spring.application.name=Todo-Project

#GitHub imagerep
github.username=Sakthivel1107
github.repo=image-storage
github.branch=main
github.token=${GITHUB_TOKEN}

spring.mongodb.uri=${DB_URI}
spring.mongodb.database=${DB_DATABASE}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.tomcat.max-swallow-size=10MB
spring.servlet.multipart.enabled=true

#Secret Key
secret.key=${SECRET_KEY}